version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG

  file:
    class: logging.FileHandler
    filename: "/app/logs/app.log"
    formatter: standard
    level: DEBUG

loggers:
  uvicorn:
    handlers: [console, file]
    level: DEBUG
    propagate: false

root:
  handlers: [console, file]
  level: DEBUG
